# Site settings
title: Extreme Air Systems Pvt. Ltd. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.jpg

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Extreme Air Systems Pvt. Ltd.
    
# Contact form
api_token: "c84e8962aca6a783d445b8a81ebf3876" # Enter API token here

# Contact info
contact:
    name: Nisarg Jani
    phone: 97273 79760
    email: info@extremeair.in
    address: "C-63, Shiv Industrial Park, Nr. Sarjan Ind., Ambica Tube Compound, Vatva, Ahmedabad – 382440, Gujarat, India."

# Map
map:
    zoom: 17
    address: Gujarat india
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
feed: yes

# Footer
copyright: © 2015 Extreme Air Systems Pvt. Ltd.

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-72221421-1
google_verification:
